---
- hosts: 'localhost'
  connection: 'local'
  vars:
    apt:
      repositories:
        - 'deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner'   # Ubuntu partners
        - 'deb http://dl.google.com/linux/chrome/deb/ stable main'                               # Google Chrome
        - 'ppa:webupd8team/sublime-text-3'                                                       # Sublime Text 3
        - 'ppa:webupd8team/atom'                                                                 # Atom
        - 'deb http://linux.dropbox.com/ubuntu {{ ansible_distribution_release }} main'          # Dropbox
      packages:
        - 'adobe-flashplugin'               # Adobe Flash plugin for browsers
        - 'aptitude'                        # Text-based frontend to apt
        - 'atom'                            # Text editor
        - 'autogen'                         # Often required for building things from source
        - 'build-essential'                 # Build tools (g++, make, etc.)
        - 'cloc'                            # Count Lines Of Code
        - 'compizconfig-settings-manager'   # Desktop environment settings tweaker
        - 'curl'                            # CLI tool for transferring data
        - 'dh-autoreconf'                   # Often required for building things from source
        - 'dropbox'                         # Cloud file storage
        - 'gimp'                            # Photoshop for neckbeards
        - 'git'                             # Distributed source control
        - 'google-chrome-stable'            # Google web browser
        - 'gprename'                        # Bulk rename utility
        - 'htop'                            # Nicer version of 'top'
        - 'inkscape'                        # Illustrator for neckbeards
        - 'libsdl1.2-dev'                   # Simple Directmedia Layer 1.2
        - 'libsdl-mixer1.2-dev'             # Audio component for SDL 1.2
        - 'libsdl-net1.2-dev'               # Networking component for SDL 1.2
        - 'ncdu'                            # Terminal-based disk treemap viewer
        - 'nodejs'                          # Node.js
        - 'npm'                             # Node Package Manager
        - 'numlockx'                        # Enable/disable numlock from the command line
        - 'p7zip-full'                      # 7zip
        - 'p7zip-rar'                       # 7zip RAR support
        - 'pithos'                          # Pandora desktop client
        - 'python-dev'                      # Python headers/lib
        - 'python-gpgme'                    # Binary verification for Dropbox
        - 'python-pip'                      # Python package manager
        - 'python3-pip'                     # Python3 package manager
        - 'synaptic'                        # GUI frontend to apt
        - 'sublime-text-installer'          # Awesome text editor
        - 'terminator'                      # Terminal emulator
        - 'tree'                            # Pretty-print directory structures
        - 'ubuntu-wallpapers*'              # Ubuntu wallpapers from the beginning of time
        - 'vagrant'                         # Development VM sandboxing
        - 'virtualbox'                      # Virtual machine provider
        - 'vim'                             # Terminal text editor
        - 'weechat'                         # Terminal IRC client
        - 'xclip'                           # Command-line interface to X clipboard
        - 'zsh'                             # Bash alternative
    development_dir: '{{ home_dir }}/Development'
    dotfiles:
      repo: 'git@github.com:rohanliston/dotfiles.git'
      dir:  '{{ home_dir }}/.dotfiles'
    home_dir: '/home/{{ user_name }}'
    repos:  # @TODO: Just clone all github repos
      - { repo: 'git@github.com:rohanliston/adobe-spritesheet-scripts.git', dest: '{{ development_dir }}/personal/adobe-spritesheet-scripts' }
      - { repo: 'git@github.com:rohanliston/babushka-deps.git'            , dest: '{{ development_dir }}/personal/babushka-deps'             }
      - { repo: 'git@github.com:rohanliston/guisignalslot.git'            , dest: '{{ development_dir }}/personal/guisignalslot'             }
      - { repo: 'git@github.com:rohanliston/html5-asteroids.git'          , dest: '{{ development_dir }}/personal/html5-asteroids'           }
      - { repo: 'git@github.com:rohanliston/qt-redis.git'                 , dest: '{{ development_dir }}/personal/qt-redis'                  }
      - { repo: 'git@github.com:ssilab/ansible-aws-cli.git'               , dest: '{{ development_dir }}/ssil/ansible-aws-cli'               }
      - { repo: 'git@github.com:ssilab/ansible-golang.git'                , dest: '{{ development_dir }}/ssil/ansible-golang'                }
      - { repo: 'git@github.com:ssilab/ansible-java.git'                  , dest: '{{ development_dir }}/ssil/ansible-java'                  }
      - { repo: 'git@github.com:ssilab/ansible-locales.git'               , dest: '{{ development_dir }}/ssil/ansible-locales'               }
      - { repo: 'git@github.com:ssilab/ansible-logrotate.git'             , dest: '{{ development_dir }}/ssil/ansible-logrotate'             }
      - { repo: 'git@github.com:ssilab/ansible-mongodb.git'               , dest: '{{ development_dir }}/ssil/ansible-mongodb'               }
      - { repo: 'git@github.com:ssilab/ansible-nodejs.git'                , dest: '{{ development_dir }}/ssil/ansible-nodejs'                }
      - { repo: 'git@github.com:ssilab/ansible-postgres.git'              , dest: '{{ development_dir }}/ssil/ansible-postgres'              }
      - { repo: 'git@github.com:ssilab/ansible-redis.git'                 , dest: '{{ development_dir }}/ssil/ansible-redis'                 }
      - { repo: 'git@github.com:ssilab/ansible-ubuntu-general.git'        , dest: '{{ development_dir }}/ssil/ansible-ubuntu-general'        }
      - { repo: 'git@github.com:ssilab/ssil-dashboard.git'                , dest: '{{ development_dir }}/ssil/ssil-dashboard'                }
    ruby:
      installed_versions:
        - '2.2.3'
      global_version: '2.2.3'
    unity:
      workspaces:
        horizontal: 2
        vertical: 2
      launcher_icons:
        - 'application://org.gnome.Nautilus.desktop'
        - 'application://google-chrome.desktop'
        - 'application://firefox.desktop'
        - 'application://thunderbird.desktop'
        - 'application://libreoffice-writer.desktop'
        - 'application://libreoffice-calc.desktop'
        - 'application://libreoffice-impress.desktop'
        - 'application://ubuntu-software-center.desktop'
        - 'application://unity-control-center.desktop'
        - 'application://x-terminal-emulator.desktop'
        - 'application://slack.desktop'
        - 'application://sublime-text.desktop'
        - 'unity://running-apps'
        - 'unity://expo-icon'
        - 'unity://devices'
    user_name: 'rohan'
  tasks:
    - include: 'tasks/ubuntu.yml'
    - include: 'tasks/packages.yml'
    - include: 'tasks/zsh.yml'
    - include: 'tasks/dotfiles.yml'
    - include: 'tasks/repos.yml'
    - include: 'tasks/slack.yml'
    - include: 'tasks/thunderbird.yml'
    - include: 'tasks/ruby.yml'
