---
- name: 'Install rcm PPA'
  tags: 'dotfiles'
  sudo: 'yes'
  apt_repository: 'repo=ppa:martin-frost/thoughtbot-rcm'

- name: 'Install rcm for dotfiles management'
  tags: 'dotfiles'
  sudo: 'yes'
  apt: >
    pkg=rcm
    update_cache=yes

- name: 'Clone dotfiles repo'
  tags: 'dotfiles'
  git: >
    repo={{ dotfiles.repo }}
    dest={{ dotfiles.dir }}
    accept_hostkey=yes

- name: 'Apply dotfiles'
  tags: 'dotfiles'
  command: 'rcup -f -d {{ dotfiles.dir }}'
