---
- name: 'Install rcm PPA'
  tags: 'dotfiles'
  sudo: 'yes'
  # No repo for utopic yet; replace with this line once one exists:
  # apt_repository: 'repo=ppa:martin-frost/thoughtbot-rcm'
  apt_repository: 'repo="deb http://ppa.launchpad.net/martin-frost/thoughtbot-rcm/ubuntu trusty main"'

- name: 'Install rcm for dotfiles management'
  tags: 'dotfiles'
  sudo: 'yes'
  apt: >
    pkg=rcm
    update_cache=yes
    force=yes

- name: 'Clone dotfiles repo'
  tags: 'dotfiles'
  git: >
    repo={{ dotfiles.repo }}
    dest={{ dotfiles.dir }}
    accept_hostkey=yes

- name: 'Apply dotfiles'
  tags: 'dotfiles'
  command: 'rcup -f -d {{ dotfiles.dir }}'
