---
- name: 'Dotfiles --> Create depot directory to contain archives'
  tags:
    - 'packages'
    - 'dotfiles'
  sudo: 'yes'
  file: >
    path=/opt/depot
    state=directory

- name: 'Dotfiles --> Download ThoughtBot rcm'
  tags: 'dotfiles'
  sudo: 'yes'
  get_url: >
    url=https://thoughtbot.github.io/rcm/debs/rcm_1.2.3-1_all.deb
    dest=/opt/depot
    mode=0664

- name: 'Dotfiles --> Install ThoughtBot rcm for dotfiles management'
  tags: 'dotfiles'
  sudo: 'yes'
  apt: deb=/opt/depot/rcm_1.2.3-1_all.deb

- name: 'Dotfiles --> Clone dotfiles repo'
  tags: 'dotfiles'
  git: >
    repo={{ dotfiles.repo }}
    dest={{ dotfiles.dir }}
    accept_hostkey=yes

- name: 'Dotfiles --> Apply dotfiles'
  tags: 'dotfiles'
  command: 'rcup -f -d {{ dotfiles.dir }}'
