---
- name: 'Homebrew --> Check Homebrew is installed'
  stat: 'path=/usr/local/bin/brew'
  register: brew_installed

- name: 'Homebrew --> Install Homebrew'
  shell: 'ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"'
  when: 'brew_installed.stat.exists == false'

- name: 'Homebrew --> Tap homebrew/dupes'
  shell: 'brew tap homebrew/dupes'

- name: 'Homebrew --> Install Homebrew libraries'
  homebrew: 'name={{ item }} state=present'
  with_items: 'brews'

- name: 'Homebrew --> Check homebrew-cask is installed'
  stat: 'path=/usr/local/bin/brew-cask.rb'
  register: 'brew_cask_installed'

- name: 'Homebrew --> Install homebrew-cask'
  shell: 'brew tap phinze/cask && brew install brew-cask'
  when: 'brew_cask_installed.stat.exists == false'

- name: 'Homebrew --> Check for installed casks'
  shell: 'brew cask list --appdir={{ application_dir }} --caskroom={{ caskroom_dir}} | grep {{ item }}'
  register: 'installed_applications'
  with_items: 'applications'
  ignore_errors: 'yes'

- name: 'Homebrew --> Install apps with brew-cask'
  shell: 'brew cask install {{ item }} --appdir={{ application_dir }} --caskroom={{ caskroom_dir }}'
  with_items: 'applications'
  when: "item not in installed_applications.results|map(attribute='stdout')"

- name: 'Homebrew --> Modify alfred scope to include caskroom'
  shell: 'brew cask alfred link --appdir={{ application_dir }} --caskroom={{ caskroom_dir }}'
