---
- name: 'Add apt repositories'
  tags: 'packages'
  sudo: 'yes'
  apt_repository: >
    repo="{{ item }}"
    state=present
  with_items: apt.repositories

- name: 'Install apt packages'
  tags: 'packages'
  sudo: 'yes'
  apt: >
    update_cache=yes
    cache_valid_time=3600
    pkg={{ item }}
    force=yes
  with_items: apt.packages

