---
- name: 'Enable apt partner repositories'
  tags: 'packages'
  sudo: 'yes'
  lineinfile: >
    dest=/etc/apt/sources.list
    line="{{ item }}"
  with_items:
    - 'deb http://archive.canonical.com/ubuntu trusty partner'
    - 'deb-src http://archive.canonical.com/ubuntu trusty partner'

- name: 'Install apt packages'
  tags: 'packages'
  sudo: 'yes'
  apt: >
    update_cache=yes
    cache_valid_time=3600
    pkg={{ item }}
    force=yes
  with_items: apt.packages

