---
- name: 'Ubuntu --> Set horizontal workspace layout'
  tags:
    - 'ubuntu'
    - 'unity'
    - 'workspaces'
  gsettings: >
    schema=org.compiz.core:/org/compiz/profiles/unity/plugins/core/
    key=hsize
    value={{ unity.workspaces.horizontal }}

- name: 'Ubuntu --> Set vertical workspace layout'
  tags:
    - 'ubuntu'
    - 'unity'
    - 'workspaces'
  gsettings: >
    schema=org.compiz.core:/org/compiz/profiles/unity/plugins/core/
    key=vsize
    value={{ unity.workspaces.vertical }}

- name: 'Ubuntu --> Set launcher pinned icons'
  tags:
    - 'ubuntu'
    - 'unity'
    - 'launcher'
  gsettings: >
    schema=com.canonical.Unity.Launcher
    key=favorites
    value="{{ unity.launcher_icons }}"

- name: 'Ubuntu --> Remove apport'
  tags:
    - 'ubuntu'
    - 'apport'
  sudo: 'yes'
  apt: >
    pkg=apport
    state=absent
    purge=yes

- name: 'Ubuntu --> Get rid of annoying avahi notifications'
  tags:
    - 'ubuntu'
    - 'avahi'
  sudo: 'yes'
  lineinfile: >
    dest=/etc/default/avahi-daemon
    line="AVAHI_DAEMON_DETECT_LOCAL=0"
    regexp="AVAHI_DAEMON_DETECT_LOCAL=1"
    backrefs=yes
