---
- name: 'Set horizontal workspace layout'
  tags: 'ubuntu'
  command: 'gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ hsize {{ workspaces.horizontal }}'

- name: 'Set vertical workspace layout'
  tags: 'ubuntu'
  command: 'gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ vsize {{ workspaces.vertical }}'

- name: 'Remove apport'
  tags: 'ubuntu'
  sudo: 'yes'
  apt: >
    pkg=apport
    state=absent
    purge=yes

- name: 'Get rid of annoying avahi notifications'
  tags: 'ubuntu'
  sudo: 'yes'
  lineinfile: >
    dest=/etc/default/avahi-daemon
    line="AVAHI_DAEMON_DETECT_LOCAL=0"
    regexp="AVAHI_DAEMON_DETECT_LOCAL=1"
    backrefs=yes
