---
- name: 'Create depot directory to contain archives'
  tags:
    - 'packages' 
  	- 'vagrant'
  sudo: 'yes'
  file: >
    path=/opt/depot
    state=directory

- name: 'Download Vagrant deb'
  tags:
    - 'packages'
    - 'vagrant'
  sudo: 'yes'
  get_url: >
    url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.5_x86_64.deb
    dest=/opt/depot

- name: 'Install Vagrant'
  tags:
    - 'packages'
    - 'vagrant'
  sudo: 'yes'
  apt: 'deb=/opt/depot/vagrant_1.6.5_x86_64.deb'