---
- name: 'Install dependencies'
  tags:
   - 'packages'
   - 'zsh'
  sudo: 'yes'
  apt: >
    pkg={{ item }}
    update_cache=yes
  with_items:
    - 'curl'
    - 'zsh'

- name: 'Determine if zsh is default/current shell'
  tags: 'zsh'
  shell: 'echo $SHELL'
  register: current_shell

- name: 'Enable zsh in /etc/shells'
  tags: 'zsh'
  sudo: 'yes'
  shell: 'sudo /bin/sh -c grep -q "/bin/zsh" /etc/shells || echo "/bin/zsh" >> /etc/shells'
  when: 'current_shell.stdout != "/bin/zsh"'

- name: 'Set zsh as default shell'
  tags: 'zsh'
  sudo: 'yes'
  user: >
    name=rohan
    shell=/bin/zsh

- name: 'Check oh-my-zsh is installed'
  tags: 'zsh'
  stat: 'path={{ home_dir }}/.oh-my-zsh'
  register: oh_my_zsh_installed

- name: 'Install oh-my-zsh'
  tags: 'zsh'
  shell: 'curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh'
  when: 'oh_my_zsh_installed.stat.exists == false'
